version: '3.8'

services:
  api:
    build: ./backend
    container_name: comp0022_fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
        - db

  db:
    image: postgres:latest
    container_name: comp0022_postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
        - "5432:5432"

volumes:
  db-data: